# Generated by Django 4.1.4 on 2023-01-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
