# Generated by Django 4.1.6 on 2023-02-12 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
