# Generated by Django 4.1.6 on 2023-02-19 03:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='retweets',
            field=models.ManyToManyField(related_name='rtposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
