# Generated by Django 4.1.6 on 2023-02-19 03:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_post_retweets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='retweets',
        ),
        migrations.AddField(
            model_name='post',
            name='shares',
            field=models.ManyToManyField(blank=True, related_name='rtposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
