# Generated by Django 4.1.6 on 2023-02-20 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_post_shared_post_delete_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shared_post',
        ),
        migrations.AddField(
            model_name='post',
            name='reposted_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='main.post'),
        ),
    ]
