# Generated by Django 4.1.6 on 2023-02-20 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_remove_post_shared_post_post_reposted_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reposted_post',
        ),
        migrations.AddField(
            model_name='post',
            name='reposts',
            field=models.ManyToManyField(blank=True, related_name='reposts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
    ]
