# Generated by Django 4.1.6 on 2023-02-20 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reposts',
        ),
    ]
